modLoader="javafml"
loaderVersion="[4,)"
license="LicenseRef-All-Rights-Reserved"
issueTrackerURL="https://github.com/Sythiex/StillWander-Neo/issues"

[[mods]]
modId="stillwander"
version="${version}"
displayName="Still Wander"
authors="Prasanna163, Sythiex"
displayURL="https://github.com/Sythiex/StillWander-Neo"
logoFile="assets/stillwander/icon.png"
description='''Stand still and let an environment-aware cinematic camera explore your Minecraft world.'''

[[mixins]]
config="stillwander.mixins.json"

[[dependencies.stillwander]]
modId="neoforge"
type="required"
versionRange="[21.1,21.2)"
ordering="NONE"
side="CLIENT"

[[dependencies.stillwander]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="CLIENT"
